### ISSUE TITLE
Replace all UInt64 with NativeUInt

### ISSUE THREAD

**Issue by JBontes** [lordcrc/DGPQueue#1]
It makes no sense having a Uint64 for a counter in win32.  
I would suggest replacing all these occurances with NativeUInt.  
That way you'll get better performance on win32.

**Comment by lordcrc** [comment]
I strongly disagree that a 32bit counter is sufficient. If you add elements at a (modest) rate of 10 MHz, a 32bit counter will overflow in 7 minutes.

Instead I would like to make the counter optional, so that those who don't need stability don't have to pay the price.

**Comment by JBontes** [comment]
How can you have more than 4billion elements in a memory space of 4GB max? That does not make sense to me. Not unless the counter monotonically increases even when you delete elements (and add new ones after that).

**Comment by lordcrc** [comment]
It's a timestamp counter, not number of elements. It's used to order elements of same priority in FIFO order. There are other ways (linked list per element for example), but I aimed for simplicity in the first iteration.

As I said, I will try to make it optional.

**Comment by JBontes** [comment]
OK that makes it clear.
